### ISSUE TITLE
TYPO3 hangs during "silent configuration update"

### ISSUE THREAD

**Issue by oheinemann** [helhum/TYPO3-Distribution#23]
I have cloned the master branch of this distribution and made no changes. When I start DDEV, log into the backend and click on "Admin Tools -> Maintenance" (or Settings, Upgrade or Environment), the apache server hangs at the step **Checking session and executing silent configuration update** and spawns PHP processes until my hair turns grey!
The processor is slowly starting to burn a hole in my MacBook. 
Unfortunately, the log shows no usable error messages.
I use DDEV in version v1.15.3. No idea if this is a DDEV problem or if the distribution does not work with TYPO3 in version 10.4.

**Comment by infabo** [comment]
usually this is helhum/config-handling which is not able to make/handle configuration migrations.

**Comment by oheinemann** [comment]
Yes, you are right. I have just found that out as well. I compared version 9.5 with version 10.4. There are three new functions in the "SilentConfigurationUpgradeService" from the "typo3/cms-install" package. "migrateCachingFrameworkCaches", "migrateMailSettingsToSendmail" and "migrateMailSmtpEncryptSetting". The error is found in the function "migrateCachingFrameworkCaches". It tries to remove the prefix "cache_" from the cache configurations, which for some reason does not work. If you manually adjust the cache configuration in the file "config/includes/dev/cache.yaml", then it works.

**Comment by localhorst** [comment]
@oheinemann 

> If you manually adjust the cache configuration in the file "config/includes/dev/cache.yaml", then it works.

What kind of adjustment is necessary?

**Comment by wimr0001** [comment]
When I started a module in "Admin tools" then I had also the message "Checking session and executing silent configuration update". This never ends.
Cause of this problem is the file "additional.php" under the directory typo3conf/system.
Deleting this file solves the problem.

The "additional.php" file caused also another problem with the form system-extension.
Updating a form resulted in an "access denied".
After deleting the "additional.php"  file, this problem was gone.
